# Generated by Django 5.0.6 on 2026-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDorkQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('query_text', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'dork de Google',
                'verbose_name_plural': 'dorks de Google',
                'db_table': 'google_dork_queries',
                'ordering': ['-added_at', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoredDomain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'dominio monitorizado',
                'verbose_name_plural': 'dominios monitorizados',
                'db_table': 'monitored_domains',
                'ordering': ['-added_at', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoredIpAddress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'IP monitorizada',
                'verbose_name_plural': 'IPs monitorizadas',
                'db_table': 'monitored_ip_addresses',
                'ordering': ['-added_at', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoredKeyword',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('term', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'palabra clave monitorizada',
                'verbose_name_plural': 'palabras clave monitorizadas',
                'db_table': 'monitored_keywords',
                'ordering': ['-added_at', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShodanDorkQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('query_text', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'dork de Shodan',
                'verbose_name_plural': 'dorks de Shodan',
                'db_table': 'shodan_dork_queries',
                'ordering': ['-added_at', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'canal de Telegram',
                'verbose_name_plural': 'canales de Telegram',
                'db_table': 'telegram_channels',
                'ordering': ['-added_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterDorkQuery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('added_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('query_text', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'dork de Twitter',
                'verbose_name_plural': 'dorks de Twitter',
                'db_table': 'twitter_dork_queries',
                'ordering': ['-added_at', '-id'],
                'abstract': False,
                'managed': False,
            },
        ),
    ]
