# Generated by Django 5.0.6 on 2026-09-18 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'db_table': 'customers',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=255)),
                ('run_started_at', models.DateTimeField(blank=True, null=True)),
                ('run_finished_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ejecucion de modulo',
                'verbose_name_plural': 'ejecuciones de modulos',
                'db_table': 'scan_runs',
                'ordering': ['-run_started_at', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalogEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'servicio del catalogo',
                'verbose_name_plural': 'catalogo de servicios',
                'db_table': 'service_catalog',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceSubscription',
            fields=[
                ('customer', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='subscription', serialize=False, to='customers.customer')),
                ('defacement_enabled', models.BooleanField()),
                ('github_enabled', models.BooleanField()),
                ('gitlab_enabled', models.BooleanField()),
                ('google_enabled', models.BooleanField()),
                ('intelx_enabled', models.BooleanField()),
                ('shodan_enabled', models.BooleanField()),
                ('telegram_enabled', models.BooleanField()),
                ('twitter_enabled', models.BooleanField()),
                ('typosquatting_enabled', models.BooleanField()),
                ('certificates_enabled', models.BooleanField()),
                ('blocklist_enabled', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'servicios contratados',
                'verbose_name_plural': 'servicios contratados',
                'db_table': 'customer_service_subscriptions',
                'ordering': ['customer_id'],
                'managed': False,
            },
        ),
    ]
